### ISSUE TITLE
ModuleNotFoundError: No module named 'quest._kernels'

### ISSUE THREAD

**Issue by Yu-Qi-hang** [mit-han-lab/Quest#14]
I installed this repository following installation instructions 1 and 2 in the README.
And this error occurs when I run the program， I don't see it in the source file either.

**Comment by happierpig** [comment]
Hi @Yu-Qi-hang ,

'quest._kernels' is used in the efficiency part, which needs the setup of customized CUDA kernels by instructions in 3 and 4. Check: https://github.com/mit-han-lab/Quest/blob/24c9c6fcac9f9e936847f511da414f1150cc9fb4/quest/ops/setup.sh#L9

**Comment by Yu-Qi-hang** [comment]
Thanks a lot for your explanation! It works now!
