### ISSUE TITLE
confuse about torch version

### ISSUE THREAD

**Issue by kengchiawu** [mit-han-lab/Quest#15]
Hi:
Thanks for the opening source!
I did not find a version that supports torch=2.5.0 in flash_attntion v2.6.3 release. Is this a typo?

**Comment by Sakits** [comment]
Hi @kengchiawu ,

Thank you for your interest in our work! Flash_attn v2.6.3 is expected to be compatible with Torch 2.5.0. Could you let us know if you encountered any specific issues or error messages while using this version? We might be able to assist you in solving them. :)
