### ISSUE TITLE
why "seq_length = max_key.shape[-2]" does exists eventhough "kv_seq_len" exists?

### ISSUE THREAD

**Issue by YEOMJINSEOP** [mit-han-lab/Quest#17]
Hi, Thanks for sharing wonderful work.

I'm a little bit confused between `seq_length = max_key.shape[-2]` and `kv_seq_len`  in quest_attention.py's `def forward`
because i think `seq_length=max_key.shape[-2]` should be equal to `kv_seq_len`.
do you have any special reason using seq_length as a separate variable?

e.g.) why seq_length is used here?
`chunk_max_key = chunk_max_key.reshape(chunk_max_key.shape[0],  chunk_max_key.shape[1],  -1, chunk_max_key.shape[-1])[:, :, :seq_length, :]`

Thanks!

**Comment by YEOMJINSEOP** [comment]
`kv_seq_len = seq_length + padding_length`

**Comment by Sakits** [comment]
Hi @YEOMJINSEOP , 

Thank you for your kind words and for taking the time to dive into the details of our code!

You’re right that `seq_length = max_key.shape[-2]` and `kv_seq_len` are numerically equal in the implementation. However, we intentionally used `seq_length` as a separate variable to enhance clarity and explicitness. This was just made to minimize potential confusion when introducing chunking or padding logic.

I hope this clarifies our implementation! Please let me know if you have further questions. :)
