### ISSUE TITLE
Error when configuring in raft

### ISSUE THREAD

**Issue by p1nksnow** [mit-han-lab/Quest#2]
When I execute the following command lines you provided,
```
cd kernels/3rdparty/raft
./build.sh libraft
```
errors occur, and the error is as follows,
```
(quest) xxxx@stresstest:~/quest/kernels/3rdparty/raft$ ./build.sh libraft
Building for the architecture of the GPU in the system...
CMake Error at CMakeLists.txt:18 (include):
  include could not find requested file:

    rapids-cmake


CMake Error at CMakeLists.txt:19 (include):
  include could not find requested file:

    rapids-cpm


CMake Error at CMakeLists.txt:20 (include):
  include could not find requested file:

    rapids-export


CMake Error at CMakeLists.txt:21 (include):
  include could not find requested file:

    rapids-find


CMake Error at CMakeLists.txt:30 (include):
  include could not find requested file:

    rapids-cuda


CMake Error at CMakeLists.txt:31 (rapids_cuda_init_architectures):
  Unknown CMake command "rapids_cuda_init_architectures".


-- Configuring incomplete, errors occurred!
(quest) xxxx@stresstest:~/quest/kernels/3rdparty/raft$ 
```

I followed your command lines exactly, without adding any other operations. This seems to be a file missing problem. Can you provide some insights on how to solve the problem so that I can better follow your work?

**Comment by happierpig** [comment]
Hi @p1nksnow ,

Thanks for your interest in our work.

Indeed, I can't reproduce the problem you met. However, I guess the issue may be related to your machine's networks. Check `kernels/3rdparty/raft/cpp/CMakeLists.txt: line 17`, which includes `kernels/3rdparty/raft/fetch_rapids.cmake` and uses
```
  file(DOWNLOAD https://raw.githubusercontent.com/rapidsai/rapids-cmake/branch-24.02/RAPIDS.cmake
       ${CMAKE_CURRENT_BINARY_DIR}/RAFT_RAPIDS.cmake
  )
```
to pull needed files. I have uploaded the pulled RAFT_RAPIDS.cmake in this [gist](https://gist.github.com/happierpig/380b8269aebd06dd4fa1d0a56ff4f6e4).

Please let me know if the issue still exists.

**Comment by p1nksnow** [comment]
Thank you for your timely reply, this is indeed due to network problems, I have solved it.👍
